"""A descriptive message for the change

Revision ID: 4d05cf15abd0
Revises: 
Create Date: 2025-10-22 19:39:05.906755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d05cf15abd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=False)
    op.create_index(op.f('ix_events_experiment_id'), 'events', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_events_timestamp'), 'events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='experimentstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('primary_metric_name', sa.String(), nullable=False),
    sa.Column('target_duration_days', sa.Float(), nullable=True),
    sa.Column('target_statistical_significance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('experiment_id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_experiments_experiment_id'), 'experiments', ['experiment_id'], unique=False)
    op.create_table('variants',
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('variant_name', sa.String(), nullable=False),
    sa.Column('traffic_allocation_percent', sa.Float(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=True),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.PrimaryKeyConstraint('variant_id')
    )
    op.create_index(op.f('ix_variants_experiment_id'), 'variants', ['experiment_id'], unique=False)
    op.create_table('assignments',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=False),
    sa.Column('assignment_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.variant_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'experiment_id', name='assignment_pk')
    )
    op.create_index(op.f('ix_assignments_experiment_id'), 'assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_assignments_user_id'), 'assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_user_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_experiment_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_variants_experiment_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_experiments_experiment_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_timestamp'), table_name='events')
    op.drop_index(op.f('ix_events_experiment_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
