"""remove created_by_user_id column from experiment

Revision ID: d95adb99a2f6
Revises: 4d05cf15abd0
Create Date: 2025-10-22 20:56:03.371973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95adb99a2f6'
down_revision: Union[str, Sequence[str], None] = '4d05cf15abd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('experiments', 'created_by_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiments', sa.Column('created_by_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
